import Head from "next/head";
import { useState } from "react";
import { motion } from "framer-motion";
import StepCard from "/components/StepCard";
import EmailCard from "/components/EmailCard";

export default function Home() {
  return (
    <div className="flex flex-grow bg-gray-800">
      <Head>
        <title>Framer Playground</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-800 w-full h-full flex items-center justify-center flex-col">
        <div className="my-36 flex flex-col items-center justify-center  px-4 md:px-0">
          <h1 className="text-gray-400 text-4xl mb-12 font-mono">
            Things Style Form Wizard
          </h1>
          <StepCard />
        </div>
        <div className="mb-36 flex flex-col w-full items-center justify-center">
          <h1 className="text-gray-400 text-4xl mb-12 font-mono">
            Email Client
          </h1>
          <EmailCard />
        </div>
      </main>

      <footer></footer>
    </div>
  );
}
